server: # REST and WS server
    port: 2333
    address: 127.0.0.1
spring:
    main:
        banner-mode: log
lavalink:
    server:
        password: "conducting"
        sources:
            youtube: true
            bandcamp: true
            soundcloud: true
            twitch: true
            vimeo: true
            http: true
            local: false
        bufferDurationMs: 400
        frameBufferDurationMs: 5000
        youtubePlaylistLoadLimit: 6
        playerUpdateInterval: 5
        youtubeSearchEnabled: true
        soundcloudSearchEnabled: false
        gc-warnings: true
        #ratelimit:
        #   ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
        #   excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
        #   strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
        #   searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
        #   retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
    prometheus:
        enabled: false
        endpoint: /metrics

sentry:
    dsn: ""
    environment: ""
#   tags:
#       some_key: some_value
#       another_key: another_value

logging:
    file:
        max-history: 30
        max-size: 1GB
        path: ./logs/
    level:
        root: INFO
        lavalink: INFO